### ISSUE TITLE
the issue of SVG or JSON file format

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#12]
Hi, 

I am wondering whether it is possible that the SVG file can include the order information of the sequence. Currently, the SVG file includes the coordination, however, the order information (from 5' end to 3' end) was not included.

another question, how to parse the JSON file output and become an image file?  

My best

**Comment by fjossinet** [comment]
Hi. 

Concerning SVG, not sure since its purpose is to store drawing instructions, not really data. What is your goal?

Concerning JSON files, they will be replaced with scripts written with the RNArtistCore language (RNArtistCore is the drawing engine inside RNArtist). RNArtist is delegating more and more stuff to its drawing engine. If you check the documentation of RNArtistCore, you will see instructions to produce a picture (you just have to add elements like svg or png). The idea is that you use RNArtist and then you save your work as scripts. And you can use these scripts without RNArtist (from the commandline, to share them,....) RNArtist becomes a kind of visual editor to produce such scripts interactively. This is why i made a new script editor synchronized with the canvas of RNArtist.

**Comment by MingleiYang** [comment]
Thank you for your reply.

As for the SVG, I noticed that for the long RNA structure, the output of SVG has different size of circle around the letters, for example(below), So i have to edit the SVG manually to make them consistent. I am thinking if the SVG can also give the order of the sequence, it will give more possibility for further editting.
<img width="212" alt="Screenshot 2021-12-29 at 18 46 20" src="https://user-images.githubusercontent.com/7471846/147694047-19ab9081-6b94-441a-98aa-977575f9abbe.png">

As for JSON, I cannot agree with more to replace it with the scripts, which is more useful.

My best,

**Comment by fjossinet** [comment]
I have already observed that. But not since a while. Do you have any sample data with such result? On which operating system are your running RNArtist?

**Comment by fjossinet** [comment]
I think i found the issue (by fixing another one ;-). Could you get the last commit for RNArtist and try?

**Comment by MingleiYang** [comment]
Hi, 

I am loading the project from the previous one to test it. however, the script edit didn't respond. see below,

![image](https://user-images.githubusercontent.com/7471846/147761303-95bb3864-e1cb-48a6-8bce-c549ef0eb137.png)

do you have any suggestion?

My best

**Comment by fjossinet** [comment]
Hi. That's normal. For the time being, the script editor will update only when you load 2D from local files (ct, bpseq,...). I have to do it for projects stored in the database now. Then you will be able to reformat your json files as scripts.

**Comment by fjossinet** [comment]
Hi. 

I have updated RNArtist. When you launch it, it asks you to choose a projects folder. Then it will move the projects in the embedded database into this folder. For each project, you will get a preview as a PNG and the data as a script using the RNArtistCore language. This is a basic conversion, only the 2D structure and the layout are targeted. The theme is not converted but you can easily get a new one with the RNArtist GUI. 
This means that you can now see your projects in the script editor and use its features to modify and save your project. I'm closing this issue. Open a new one if you find new problems.

Best
