### ISSUE TITLE
Compile Error on Ubuntu 18.04.5 with OpenJDK and Maven installed

### ISSUE THREAD

**Issue by patbohn** [fjossinet/RNArtist#2]
Hello,
While following the instructions to install, I came across this compile error:

```
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /home/patrick/tools/RNArtist/RNArtist/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:00 min
[INFO] Finished at: 2021-01-04T11:52:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (java-compile) on project rnartist: Fatal error compiling: error: release version 15 not supported -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The installed version of java is:
```
$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```

The maven version is:

```
$ mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-52-generic", arch: "amd64", family: "unix"
```

**Comment by patbohn** [comment]
Update: I have now compiled it successfully by changing java.version from 15 to 11 in the pom.xml file. 

However, when I now try to register, the Error "Connection refused" shows up.

**Comment by fjossinet** [comment]
Hi. 

The registering step is not active now. You can cancel this step. I will remove the registration step for the official release and will come back later to its implementation.

**Comment by fjossinet** [comment]
I have inactivated the user registration in the last commit. Let me know if it works. Thanks

**Comment by patbohn** [comment]
I see, yes the software itself started up after cancelling, so that's working fine, and I could successfully import your examples! 

If you're interested in some feedback, I've noticed a few things about file import:
- loading from ".fa" instead of ".fasta" does not work
- Underscores in file and fasta headers are ignored (in "2Ds Available")
And two graphical issues:
- Details Level changes doesn't update after zooming with scroll wheel (scrolling results in bases not being drawn); however right-click dragging enables base draw; 
- the underlining black line is desynced (start of the line corresponds to midpoint of sequence); this appears to be a desync of the black line because clicking "Fit 2D" puts the start of the black line into the center of the screen instead of the left border; desync happens during zooming with scrollwheel


Then lastly I would like to recommend two features that I think would be very useful for RNA (which I understand may fall behind priorities, but sadly I am no use in java to implement it ...):
- custom coloring from a text file (e.g. csv/tsv with per-position RGB, or 1D float "reactivity" data which could then be converted into a selectable colorscale inside RNArtist); would be great for probing data 
- import/edit secondary structure separately from sequence, i.e. switch through different folds for one RNA


I hope you find some of this useful. Best wishes, 
Patrick

**Comment by fjossinet** [comment]
Thank you Patrick for your nice feedback:
- loading from ".fa" instead of ".fasta" will be fixed in next commit
- Underscores in file and fasta headers are ignored (in "2Ds Available"): sharp observation. Surprisingly, no difference in the code between vienna and bpseq files parsing concerning the name of files and RNA sequences. But this issue occurs only for Vienna files. JavaFX issue related to setMnemonicParsing() for menu items.  Will be fixed in next commit.
- the zooming function is still buggy, i have to fix it. Which underlining black line is it?
- after the first release (soon) i will add features to link data to the 2D. The plan is to have a panel for each data set allowing to define the function linking a gradient color to the data distribution
- have to think about this point. Threading a new sequence in the current 2D is not difficult. Changing the 2D interactively (if this is what you means) could be tricky. The construction of the 2D drawing is making connections between several elements in order to make the 2D manipulation smooth. Changing the 2D means disrupting some connections and making new ones with care. Have to test.

Fabrice

**Comment by fjossinet** [comment]
Commit done
