### ISSUE TITLE
sequence cannot show and structure was modified

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#5]
Hi,

Thank you for your great efforts for generating this software.

recently I found there are some issue about the software,

for example,

>bit130
gcagcaggaagcacuaugggcgcagcgucaaugacgcugacgguacaggccagacaauuauugucugauauagugcAGCAGCAGAACAAUUUGCUGAGGGCUAUUGAGGCGCAACAGCAUCUGUUGCAACUCACAGUCUGGGGCAUCAAACAGCUCCAGGCAAGAAUccuggcugu 
(((((((((.((((((((..(((((((((...))))))).))........((((((.....)))))).)))))))).((((((((......(((((...(((....))...)..)))))))))))))........(((((((((........))))))))).....)))).)))))
  

showing this result:
![Screenshot 2021-11-13 at 10 15 33](https://user-images.githubusercontent.com/7471846/141614949-40d05b52-8234-4235-a115-88b6aaf57bc6.png)

1, there are "X"
2, the red bond was ignored by RNArist.

Btw, when the RNAstructure is more than 600nt. the software cannot save the figure which can show the charactors of the nucleotides. It can only show the skelton of the structure. is there any way to show the big RNA structure with the nucleotide able to be shown?

My best,

Thank you

**Comment by fjossinet** [comment]
Hi,

Thank you for giving RNArtist a try. The X residues are due to the fact that you have lower-case letters in your sequence. You're right concerning the letters during saving. It was an old check to not display them if the font size is lower than a given cutoff.

I have fixed and pushed both issues (they were located in the drawing engine RNArtistCore). From your RNArtist directory type the following to recover the new version of RNArtistCore:

`mvn clean package exec:exec`

Let me know if it works

**Comment by MingleiYang** [comment]
Hi, 

It worked. it is fantasitc.

Thank you very much.

My best

**Comment by fjossinet** [comment]
Great! Thank you. I'm closing the issue then.
Best
